apiVersion: v1
kind: Namespace
metadata:
  name: tools
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tools
  name: chat-ui-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-ui-app
  template:
    metadata:
      labels:
        app: chat-ui-app
    spec:
      containers:
      - name: chat-ui-container
        image: python:3.8-slim
        ports:
        - containerPort: 8000
        env:
        - name: LLM_API_KEY
          value: "None"
        - name: LLM_MODEL
          value: "phi-2"
        - name: LLM_BASE_URL
          value: "http://178.62.13.8:31095"
        - name: RETRIEVER_BASE_URL
          value: "http://178.62.13.8:31645"
        - name: RETRIEVER_API_KEY
          value: "None"
        - name: CHAT_USE_AUTH
          value: "True"
        - name: USERNAME
          value: "Adam"
        - name: PASSWORD
          value: "kalavai"
        command: ["/bin/sh", "-c"]
        args:
        - |
          apt-get update && apt-get install -y git
          ls
          git clone https://github.com/kalavai-net/tool_library.git /app/tool_library
          cd /app/tool_library
          git checkout feature/updates          
          cd tool_library
          cd example_tools
          cd chat_ui
          pip install -r requirements.txt
          apt-get update -y
          apt-get install -y gettext
          sh prepare.sh
          chainlit run chat_ui.py -h --port 8000
        resources:
          limits:
            cpu: 2
            memory: "4Gi"
          requests:
            cpu: 2 
            memory: "4Gi"
        volumeMounts:
        - name: chat-ui-storage
          mountPath: "/tool"
      restartPolicy: Always
      volumes:
      - name: chat-ui-storage
        #persistentVolumeClaim:
        #  claimName: chat-ui-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: chat-ui-service
  namespace: tools
  labels:
    app: chat-ui-app
spec:
  selector:
    app: chat-ui-app
  ports:
    - name: http
      port: 8000
      #nodePort: 32701
  type: NodePort
---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: chat-ui-pvc
#  namespace: tools
#spec:
#  storageClassName: longhorn-nr # Replace with your storage class name
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 1Gi # Adjust the storage size as needed
#---