apiVersion: v1
kind: Namespace
metadata:
  name: tools
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tools
  name: combined-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: combined-app
  template:
    metadata:
      labels:
        app: combined-app
    spec:
      containers:
      - name: rag-tool-container
        image: python:3.8-slim
        ports:
        - containerPort: 8000
        env:
        - name: RAG_USE_AUTH
          value: "False"
        - name: RAG_MASTER_KEY
          value: ""
        command: ["/bin/sh", "-c"]
        args:
        - |
          apt-get update && apt-get install -y git
          git clone https://github.com/kalavai-net/tool_library.git /app/tool_library
          cd /app/tool_library
          git checkout feature/updates
          pip install fastapi uvicorn
          cd tool_library/example_tools/rag
          pip install -r requirements.txt
          uvicorn api:app --host 0.0.0.0 --port 8000
        resources:
          limits:
            cpu: "2"
            memory: "4Gi"
          requests:
            cpu: "1"
            memory: "2Gi"
        volumeMounts:
        - name: shared-storage
          mountPath: "/tool"
      - name: chat-ui-container
        image: python:3.11-slim
        ports:
        - containerPort: 8001
        env:
        - name: LLM_API_KEY
          value: "None"
        - name: LLM_MODEL
          value: "phi-2"
        - name: LLM_BASE_URL
          value: "http://localhost:8000"
        - name: RETRIEVER_BASE_URL
          value: "http://localhost:8000"
        - name: RETRIEVER_API_KEY
          value: "None"
        - name: CHAT_USE_AUTH
          value: "True"
        - name: USERNAME
          value: "Adam"
        - name: PASSWORD
          value: "kalavai"
        command: ["/bin/sh", "-c"]
        args:
        - |
          apt-get update && apt-get install -y git gettext
          pip install chainlit
          git clone https://github.com/kalavai-net/tool_library.git /app/tool_library
          cd /app/tool_library
          git checkout feature/updates          
          cd tool_library/example_tools/chat_ui
          pip install -r requirements.txt
          sh prepare.sh
          chainlit run chat_ui.py --port 8001
        resources:
          limits:
            cpu: "2"
            memory: "4Gi"
          requests:
            cpu: "1"
            memory: "2Gi"
        volumeMounts:
        - name: shared-storage
          mountPath: "/data"
      restartPolicy: Always
      volumes:
      - name: shared-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: chat-ui-service
  namespace: tools
spec:
  selector:
    app: combined-app
  ports:
  - name: chat-ui
    port: 8001
    targetPort: 8001
    #nodePort: 30001 # Specify a nodePort in the range allowed by your cluster (usually 30000-32767)
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: rag-tool-service
  namespace: tools
spec:
  selector:
    app: combined-app
  ports:
  - name: rag-tool
    port: 8000
    targetPort: 8000
    #nodePort: 30001 # Specify a nodePort in the range allowed by your cluster (usually 30000-32767)
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: combined-service
  namespace: tools
spec:
  selector:
    app: combined-app
  ports:
  - name: rag-tool
    port: 8000
    targetPort: 8000
  - name: chat-ui
    port: 8001
    targetPort: 8001
  type: ClusterIP
