apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tools-library-ingress
  namespace: default
spec:
  rules:
    - host: secure.kalavai.net
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: tool-library-service
                port:
                  number: 8000
            path: /tools
  # This section is only required if TLS is to be enabled for the Ingress
  tls:
  - hosts:
    - secure.kalavai.net
    secretName: test-tls