apiVersion: v1
kind: Namespace
metadata:
  name: tools
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tools
  name: rag-tool-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-tool-app
  template:
    metadata:
      labels:
        app: rag-tool-app
    spec:
      containers:
      - name: rag-tool-container
        image: python:3.8-slim
        env:
        ports:
        - containerPort: 8000
        env:
        - name: RAG_USE_AUTH
          value: "False"
        - name: RAG_MASTER_KEY
          value: ""
        command: ["/bin/sh", "-c"]
        args:
        - |
          apt-get update && apt-get install -y git
          ls
          git clone https://github.com/kalavai-net/tool_library.git /app/tool_library
          cd /app/tool_library
          git checkout feature/updates
          # install fast api
          pip install fastapi
          pip install uvicorn
          ls
          cd tool_library
          ls
          cd example_tools
          ls
          cd rag
          pip install -r requirements.txt
          ls
          uvicorn api:app --host 0.0.0.0 --port 8000
        resources:
          limits:
            cpu: 2
            memory: "4Gi"
          requests:
            cpu: 2 
            memory: "4Gi"
        volumeMounts:
        - name: rag-tool-storage
          mountPath: "/tool"
      restartPolicy: Always
      volumes:
      - name: rag-tool-storage
        #persistentVolumeClaim:
        #  claimName: rag-tool-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: rag-tool-service
  namespace: tools
  labels:
    app: rag-tool-app
spec:
  selector:
    app: rag-tool-app
  ports:
    - name: http
      port: 8000
      #nodePort: 32701
  type: NodePort